add simple parser nokogiri
NikiTikiTavi93/flashcards pull request #5
Opened 2016-09-25 18:01 UTC by NikiTikiTavi93

2016-09-25 18:28 UTC, IvanShamatov commented on db/seeds.rb
> +            review_date: Time.zone.today)
Зачем ты проставляешь дату? У тебя же есть колбек на это

2016-09-25 18:30 UTC, IvanShamatov commented on db/seeds.rb
> +namespace :db do
Всё что есть в этом файле итак будет вызвано при rails db:seed, тебе не нужно переопределять эту задачу

2016-09-25 18:31 UTC, IvanShamatov commented on db/seeds.rb
> +    page = Nokogiri::HTML(open(PAGE_URL))
Как грустно, ты собрал слова только с этой страницы, а их там вроде аж 12, было бы неплохо доделать.

2016-09-25 18:31 UTC, IvanShamatov requested changes

2016-09-25 18:32 UTC, NikiTikiTavi93 commented on db/seeds.rb
> +    page = Nokogiri::HTML(open(PAGE_URL))
эту задачу обязательно доделаю

2016-09-26 14:34 UTC, IvanShamatov commented on db/seeds.rb
> +namespace :db do
ты всё еще оборачиваешь это в db:seed?

2016-09-26 14:35 UTC, IvanShamatov commented on app/models/card.rb
> +    self[:review_date] = date
зачем ты так сделал? было всё правильно

2016-09-26 14:36 UTC, IvanShamatov commented on db/seeds.rb
> +                       review_date: Time.zone.today)
у тебя же проставляется review_date в колбеке. У меня ощущение дежавю появляется

2016-09-26 14:36 UTC, IvanShamatov requested changes

2016-09-27 07:06 UTC, merged